"use client";

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { PageHeader } from '@/components/ui/page-header';
// ... rest of imports
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { PriorityLevel } from '@/types/service-request';
import { ArrowLeft, Send, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { z } from 'zod';

// Zod schema for server-side style validation
const serviceRequestSchema = z.object({
  title: z.string().min(1, 'Title is required').max(250, 'Title must be 250 characters or less'),
  description: z.string().min(1, 'Description is required').max(5000, 'Description must be 5000 characters or less'),
  priority_level: z.enum(['Low', 'Medium', 'High']),
  service_request_type_id: z.string().uuid('Invalid request type'),
});

interface ServiceType {
  id: string;
  name: string;
}

interface ServiceRequestType {
  id: string;
  name: string;
  service_type_id: string;
  department: {
    id: string;
    name: string;
  };
  default_priority_level: string | null;
}

export default function NewRequest() {
  const router = useRouter(); // Changed from useNavigate
  const { user } = useAuth();
  const [serviceTypes, setServiceTypes] = useState<ServiceType[]>([]);
  const [requestTypes, setRequestTypes] = useState<ServiceRequestType[]>([]);
  const [statuses, setStatuses] = useState<{ id: string; name: string }[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [selectedServiceType, setSelectedServiceType] = useState<string>('');
  const [selectedRequestType, setSelectedRequestType] = useState<string>('');
  const [selectedPriority, setSelectedPriority] = useState<PriorityLevel>('Medium');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setIsLoading(true);

    // Fetch service types
    const { data: stData } = await supabase
      .from('service_types')
      .select('id, name')
      .order('sequence');

    if (stData) setServiceTypes(stData);

    // Fetch request types with department info
    const { data: rtData } = await supabase
      .from('service_request_types')
      .select(`
        id,
        name,
        service_type_id,
        default_priority_level,
        department:service_departments(id, name)
      `)
      .order('sequence');

    if (rtData) setRequestTypes(rtData as ServiceRequestType[]);

    // Fetch statuses
    const { data: statusData } = await supabase
      .from('service_request_statuses')
      .select('id, name')
      .eq('system_name', 'PENDING')
      .single();

    if (statusData) setStatuses([statusData]);

    setIsLoading(false);
  };

  const filteredRequestTypes = requestTypes.filter(
    rt => rt.service_type_id === selectedServiceType
  );

  const selectedRequestTypeDetails = requestTypes.find(
    rt => rt.id === selectedRequestType
  );

  useEffect(() => {
    if (selectedRequestTypeDetails?.default_priority_level) {
      setSelectedPriority(selectedRequestTypeDetails.default_priority_level as PriorityLevel);
    }
  }, [selectedRequestTypeDetails]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validate with Zod before submitting
    const validationResult = serviceRequestSchema.safeParse({
      title: title.trim(),
      description: description.trim(),
      priority_level: selectedPriority,
      service_request_type_id: selectedRequestType,
    });

    if (!validationResult.success) {
      const errors = validationResult.error.errors;
      toast.error(errors[0]?.message || 'Validation failed');
      return;
    }

    setIsSubmitting(true);

    // Get pending status
    const { data: pendingStatus } = await supabase
      .from('service_request_statuses')
      .select('id')
      .eq('system_name', 'PENDING')
      .single();

    // Request number is auto-generated by database trigger
    // We pass empty string which trigger will replace with actual value
    const { data: insertedRequest, error } = await supabase
      .from('service_requests')
      .insert([{
        request_no: '', // Will be overwritten by database trigger
        requester_id: user?.id,
        service_request_type_id: validationResult.data.service_request_type_id,
        title: validationResult.data.title,
        description: validationResult.data.description,
        priority_level: validationResult.data.priority_level,
        status_id: pendingStatus?.id,
      }])
      .select('request_no')
      .single();

    if (error) {
      // Handle constraint violations with user-friendly messages
      if (error.message.includes('title_length')) {
        toast.error('Title is too long (max 250 characters)');
      } else if (error.message.includes('description_length')) {
        toast.error('Description is too long (max 5000 characters)');
      } else {
        toast.error('Failed to submit request');
      }
      console.error(error);
    } else {
      toast.success('Service request submitted successfully!', {
        description: `Request No: ${insertedRequest?.request_no}`,
      });
      router.push('/requests');
    }

    setIsSubmitting(false);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in max-w-3xl mx-auto">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => router.back()}>
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <PageHeader
          title="New Service Request"
          description="Fill in the details below to submit a new request"
        />
      </div>

      <form onSubmit={handleSubmit}>
        <Card>
          <CardHeader>
            <CardTitle>Request Details</CardTitle>
            <CardDescription>
              Provide information about your service request
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Service Type */}
            <div className="grid gap-2">
              <Label htmlFor="serviceType">Service Category *</Label>
              <Select value={selectedServiceType} onValueChange={setSelectedServiceType}>
                <SelectTrigger id="serviceType">
                  <SelectValue placeholder="Select a service category" />
                </SelectTrigger>
                <SelectContent>
                  {serviceTypes.map(type => (
                    <SelectItem key={type.id} value={type.id}>
                      {type.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Request Type */}
            <div className="grid gap-2">
              <Label htmlFor="requestType">Request Type *</Label>
              <Select
                value={selectedRequestType}
                onValueChange={setSelectedRequestType}
                disabled={!selectedServiceType}
              >
                <SelectTrigger id="requestType">
                  <SelectValue placeholder={selectedServiceType ? "Select request type" : "First select a service category"} />
                </SelectTrigger>
                <SelectContent>
                  {filteredRequestTypes.map(type => (
                    <SelectItem key={type.id} value={type.id}>
                      <div className="flex flex-col">
                        <span>{type.name}</span>
                        <span className="text-xs text-muted-foreground">{type.department?.name}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {selectedRequestTypeDetails && (
                <p className="text-sm text-muted-foreground">
                  Will be handled by: {selectedRequestTypeDetails.department?.name}
                </p>
              )}
            </div>

            {/* Priority */}
            <div className="grid gap-2">
              <Label htmlFor="priority">Priority Level *</Label>
              <Select value={selectedPriority} onValueChange={(v) => setSelectedPriority(v as PriorityLevel)}>
                <SelectTrigger id="priority">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Low">
                    <div className="flex items-center gap-2">
                      <span className="w-2 h-2 rounded-full bg-priority-low" />
                      Low - Can wait a few days
                    </div>
                  </SelectItem>
                  <SelectItem value="Medium">
                    <div className="flex items-center gap-2">
                      <span className="w-2 h-2 rounded-full bg-priority-medium" />
                      Medium - Needs attention soon
                    </div>
                  </SelectItem>
                  <SelectItem value="High">
                    <div className="flex items-center gap-2">
                      <span className="w-2 h-2 rounded-full bg-priority-high" />
                      High - Urgent, impacts work
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Title */}
            <div className="grid gap-2">
              <Label htmlFor="title">Request Title *</Label>
              <Input
                id="title"
                placeholder="Brief summary of your request"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                required
                maxLength={250}
              />
              <p className="text-xs text-muted-foreground text-right">{title.length}/250</p>
            </div>

            {/* Description */}
            <div className="grid gap-2">
              <Label htmlFor="description">Description *</Label>
              <Textarea
                id="description"
                placeholder="Please provide detailed information about your request..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                required
                rows={5}
                maxLength={2000}
              />
              <p className="text-xs text-muted-foreground text-right">{description.length}/2000</p>
            </div>

            {/* Attachments - Feature coming soon */}
            {/* File upload functionality will be implemented with proper security controls */}
          </CardContent>
        </Card>

        {/* Submit */}
        <div className="flex justify-end gap-3 mt-6">
          <Button type="button" variant="outline" onClick={() => router.back()}>
            Cancel
          </Button>
          <Button
            type="submit"
            className="gap-2 gradient-primary"
            disabled={!selectedRequestType || !title || !description || isSubmitting}
          >
            {isSubmitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Submitting...
              </>
            ) : (
              <>
                <Send className="h-4 w-4" />
                Submit Request
              </>
            )}
          </Button>
        </div>
      </form>
    </div>
  );
}
